name: build-ax3600-openclash

on:
  workflow_dispatch:        
  push:                      
    branches:
      - build-ax3600-openclash


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git \
            libncurses5-dev libncursesw5-dev libssl-dev python3-distutils python3-setuptools rsync unzip zlib1g-dev \
            file wget libelf-dev ecj fastjar upx-ucl rename

      - name: Add OpenClash feed (if missing)
        run: |
          if ! grep -q "vernesong/OpenClash" feeds.conf.default; then
            echo 'src-git openclash https://github.com/vernesong/OpenClash.git' >> feeds.conf.default
          fi
          cat feeds.conf.default

      - name: Update & install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Use AX3600 + OpenClash config
        run: |
          cp configs/ax3600-openclash.config .config
          make defconfig
          grep -E "TARGET_|luci-app-openclash" .config || true

      - name: Download sources
        run: |
          make download -j8 V=s

      - name: Compile
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-ax3600-openclash
          path: |
            bin/targets/**/ipq807x/*
            bin/packages/**/*
